### ISSUE TITLE
Refactor FlowTopology - flatten and simplify

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#123] opened 2017-12-15 06:17 UTC
There are a few things to accomplish with this refactoring (some of these will depend on whether it is first in the "flatten and simplify" backlog for topologies).

- [ ] First round with just FLOW CRUD
  - [x] Add use-case makefile
  - [x] Add use-case design
  - [ ] Fill in the makefile and design docs
    - [ ] who does it expect to receive information from (anyone and right format?)? 
    - [ ] who does it expect to send information to and why? (is to a broadcast or some unicasts?)
    - [ ] for each of the above, if there is state (beyond remembering topology), what are the state transitions?
  - [ ] Validate each step (ie developer setup and execution example)
  - [ ] Evaluate Unit Tests (sufficient?)
  - [ ] Evaluate ATDD (mvp1 vs mvp1.1 .. etc)
- [ ] Second round with FLOW Health checks
  - [ ] Update the makefile and design docs
  - [ ] Validate each step (ie developer setup and execution)
  - [ ] Evaluate Unit Tests (sufficient?)
  - [ ] Evaluate ATDD (mvp1 vs mvp1.1 .. etc)
- [ ] Simplify the Topology Creation portion
  - [ ] Are the names for bolts and spouts significant? If not, and it's boilerplate, then simplify the code
  - [ ] Can we leverage a fluent style to build up topologies?
- [ ] Simplify the number of Bolts
  - [ ] Is it possible to use a single bolt and a larger class, with the bolt interacting with the larger class, to simplify and flatten the bolts and streams
- [ ] Fix any broken unit tests
- [ ] Add new unit tests if necessary
- [ ] Fix any broken Acceptance Tests
- [ ] Ann any missing Acceptance Tests

**Comment by carmine** [comment] 2018-08-09 23:49
Related to #472 - Hub and Spoke

**Comment by pzakatov** [comment] 2019-02-11 00:06
will be a part of H&S. Duplicate of #1866 and #2017

**Closed by pzakatov** 2019-02-11 00:06 UTC
Labels: area/arch, area/topo, priority/2-high, refactor, size/5d
