### ISSUE TITLE
Path Redundancy (and Diverse)

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#1861] opened 2019-01-09 23:16 UTC
Path Redundancy leverages Path Diversity (anti-affinity) to establish 2 distinct paths between ingress/egress. There is an option as to whether it is active-active or active-passive.

Active-passive means that the alternate path is reserved (bandwidth) and most of the path should be programmed (ie everything except ingress in both directions). The benefit here is only 1 switch will need to be programmed to activate the passive flow.

Blocked by #1231

**Comment by pzakatov** [comment] 2019-01-10 06:00
looks duplicate of #1232

**Comment by carmine** [comment] 2019-01-10 06:01
duplicate of #1232

**Comment by pzakatov** [comment] 2019-10-30 12:09
done

**Closed by pzakatov** 2019-10-30 12:09 UTC
Labels: area/arch, feature, priority/2-high
