### ISSUE TITLE
ISL status won't change to Moved when physically replugging ISL

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#815] opened 2018-05-22 10:56 UTC
*Steps*
1. given 3 switches, two of them connected: (S1)-[port1] => [port1]-(S2)    (S3)
2. when disconnect S1 from S2 (important: bring port1 down on **src switch** SW1 in case of any intermediate switches in between), and then connect it to S3 and bring the port back up so that it becomes
(S1)-[port1] => [port1]-(S3)    (S2)
3. then
expected: S1 -> S2 link becomes Moved, S1 -> S3 link becomes discovered
actual: S1 -> S2 link becomes FAILED

**Comment by npliashechnikov** [comment] 2018-08-13 15:31
As of Kilda build 20180808T0912.781.ef59c57, the issue is reproducible again - ISL status changes to 'failed' as of second replug.

**Comment by sergii-iakovenko** [comment] 2018-08-28 14:27
The issue has been fixed by #1181, the ATDD-Staging tests need an update #1213.

**Closed** 2018-08-28 14:27 UTC
Labels: bug, priority/1-highest
