### ISSUE TITLE
KafkaMessageCollector complains on offset commit failure (solution: implement HandleRebalance)

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#297] opened 2018-02-14 13:39 UTC
The following message is observed in kilda-floodlight's logs:
```
Auto-commit of offsets {kilda.speaker-1=OffsetAndMetadata{offset=103122, metadata=''}, kilda.speaker-0=OffsetAndMetadata{offset=14244, metadata=''}} failed for group floodlight: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
```

KafkaMessageCollector instantiates an instance of KafkaConsumer with the auto-commit option enabled, which causes consumer offsets to be committed asynchronously and in the background. However,  the error periodically occurred on the staging environment and the recommended solution with "max.poll.records" is not applicable as KafkaConsumer in the most of these cases had no messages to process.

### Expected behavior
KafkaConsumer consumes messages from Kafka topics and successfully commits the offset.

### Steps to reproduce
TBD

**Comment by abochkarev** [comment] 2018-08-08 08:31
@sergii-iakovenko Could you please add steps to reproduce?

**Comment by abochkarev** [comment] 2018-08-09 08:34
@sergii-iakovenko Ok, I got it.

**Comment by abochkarev** [comment] 2018-08-14 07:39
@dpoltavets Please investigate.

**Comment by abochkarev** [comment] 2018-08-15 07:51
Deep research showed that such a group of errors doesn't appear in kibana logs in staging and prod anymore. Latest messages dated in staging on July 19th, 2018 and in prod on July 30th, 2018.
Proofs:
https://kibana.sirius.pn.telstra.com:5601/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(type,message,'@timestamp'),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'kilda-*',key:tags,negate:!f,type:phrase,value:kilda-floodlight),query:(match:(tags:(query:kilda-floodlight,type:phrase))))),index:'kilda-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'%22Auto-commit%20of%20offsets%20%22')),sort:!('@timestamp',asc))

https://kibana-proxy.polaris.production.pen/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!('@timestamp',message),index:'kilda-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'%22Auto-commit%20of%20offsets%20%22')),sort:!('@timestamp',desc))

It looks like this issue either "floating" or has already been fixed.

**Comment by abochkarev** [comment] 2018-08-15 07:52
I suggest monitoring this issue during the one week period. If this issue is not appear, let's close it.

**Closed** 2022-04-21 13:27 UTC
Labels: bug, techdebt, priority/4-low
