### ISSUE TITLE
Storm topology reads ALL kafka messages after (re)start

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#108] opened 2017-12-12 09:20 UTC
All produced kafka spouts are configured to read kafka topics from "-1L"... as result on each topology (re)start it rereads and "replay" all messages from connected topics. 

It is extremely bad for "production work". We should "track" kafka's offset pointer and use it as start point when we create kafka spouts.

**Comment by carmine** [comment] 2018-02-08 06:52
Is this still the case?  It reads "from earliest" .. but that should be just unread messages.

**Comment by nikitamarchenko** [comment] 2018-02-09 17:17
faced with this on current staging env

**Comment by nikitamarchenko** [comment] 2018-02-12 06:30
#276 should fix that

**Comment by jac0by** [comment] 2018-02-13 12:01
With #276, WFM uses Storm's KafkaSpout which relies on [new consumer API](http://kafka.apache.org/documentation.html#newconsumerapi). This means the offset is storing in the "__consumer_offsets" kafka topic. And although, the offset is not committed automatically by Kafka consumer, Storm's KafkaSpout handles this via [a background process](https://github.com/apache/storm/blob/e40d213de7067f7d3aa4d4992b81890d8ed6ff31/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L115) that [commits the offset manually](https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#rebalancecallback). 

Furthermore, using Kafka Spout 1.2.0 and later ([STORM-2914](https://issues.apache.org/jira/browse/STORM-2914)) the offset commit is expected to be handled in accordance with a level of [guaranteed processing](http://storm.apache.org/releases/current/Guaranteeing-message-processing.html). So along with the next version upgrade we have to set appropriate processing guarantee level.

Watching for __consumer_offsets topic on staging and dev environments confirms that the offset is persistent.

The issue is resolved by #276.

**Closed** 2018-02-13 12:07 UTC
Labels: release_blocker
