### ISSUE TITLE
Flow between multitable and non-multitable switches has invalid path properties

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#4339] opened 2021-06-29 07:03 UTC
A flow created / updated / rerouted between multitable and non-multitable switches eventually gets a path with invalid src_with_multi_table / dst_with_multi_table properties. As the result, Kilda ignores such path on the next update / reroute and leaves excess rules on the path switches.

**Comment by rtretyak** [comment] 2021-06-29 13:52
Had no luck with reproducing this on actual codebase.
Tried all combinations of creating flow with multi/single-table endpoint switches, tried changing switch modes after/before creating the flow, rerouting the flow after doing the change. Also, non of the existing autotest scenarios is able to reproduce it.
The described issue may be a leftover db inconsistency after the migration in #3946

**Comment by niksv** [comment] 2023-03-06 13:10
Won't fix because single table mode is [deprecated](https://github.com/telstra/open-kilda#deprecation)

**Closed by niksv** 2023-03-06 13:10 UTC
Labels: bug
