### ISSUE TITLE
Topology engine reads ALL kafka messages after restart

### ISSUE THREAD

**Issue by PinGwynn** [telstra/open-kilda#102] opened 2017-12-07 16:03 UTC
After redeployment/or just restarting topology engine it tries to re-read and re-play all kafka messages.

If we were running several atdd tests and restart topology engine, it tries to replay all messages.

**Comment by surabujin** [comment] 2017-12-13 09:51
My estimate 1-3d

**Comment by carmine** [comment] 2018-01-22 00:26
Seems to be a duplicate of #108 .. or at least they are related and should be solved together.

**Closed by carmine** 2018-01-22 00:26 UTC
