### ISSUE TITLE
HA-Flow: Reroute: Sub-flows are stuck in 'In-progress' status when ha-flow status is 'Up'

### ISSUE THREAD

**Issue by yuliiamir** [telstra/open-kilda#5411] opened 2023-09-29 15:18 UTC
Due to the existing logic, ha-flow rerouting is called automatically when ISL is in INACTIVE status as the required port was switched off. 

It seems like the issue was caused by these attempts to reroute the ha-flow when its ISL is INACTIVE, but there are some additional ISLs that can be used(ports were switched off one by one and there was some delay (request execution) during switching off all required ports). 

STR: 
1. Execute test  "HA-flow in 'Down' status is rerouted when discovering a new ISL" several times  
2. (use @Unroll and where i << (1..10)).
test version: develop 58003e44 or rollback changes https://github.com/telstra/open-kilda/pull/5410

**Comment by pkazlenka** [comment] 2023-10-02 09:04
Duplicate of #5301

**Closed by pkazlenka** 2023-10-02 09:04 UTC
